language: python
python:
  - "3.6"
# command to install dependencies
install:
  - "pip install pipenv"
  - "pipenv install"

# command to run tests
script: "pipenv run python -m unittest discover tests"
